name: CI-laravel

on:
  pull_request:
    branches: 
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Run docker compose
        run: docker-compose up -d --build

      - name: See docker compose container running
        run: docker-compose ps

      - name: PhpUnit Tests
        run: |
          ls
          cd www/
          ls
          php vendor/bin/phpunit
#        run: |
#          ls
#          docker-compose exec -T app bash
#          vendor/bin/phpunit   