name: CI-laravel

on:
  pull_request:
    branches: 
      - develop

defaults:
  run:
    working-directory: www

jobs:
  check-application:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Run docker compose
        run: docker-compose up -d --build

      - name: Setting Permissions
        run: docker-compose exec -T app chown -R www-data:www-data .

      - name: Composer update
        run: docker-compose exec -T app composer update

      - name: Composer Install
        run: docker-compose exec -T app composer install
        
      - name: Copy .env
        run: docker-compose exec -T app cp .env.example .env

      - name: Copy .env.testing
        run: docker-compose exec -T app cp .env.testing.example .env.testing

      - name: Run key generate
        run: docker-compose exec -T app php artisan key:generate

      - name: Run migrations
        run: docker-compose exec -T app php artisan migrate

      - name: Run phpunit
        run: docker-compose exec -T app php vendor/bin/phpunit

#      - name: See docker compose container running
#        run: docker-compose ps

#      - name: PhpUnit Tests
#        run: |
#          cd www/
#          ls
#          php vendor/bin/phpunit
#        run: |
#          ls
#          docker-compose exec -T app bash
#          vendor/bin/phpunit   