name: CI-laravel

on:
  pull_request:
    branches: 
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Run docker compose
        run: docker-compose up -d --build

      #- name: Setting Permissions
      #  run: chown -R www-data:www-data .
        
      - name: Copy .env
        run: cp .env.example .env

      - name: Copy .env.testing
        run: cp .env.testing.example .env.testing

      - name: Run key generate
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate

      - name: Run phpunit
        run: php vendor/bin/phpunit

#      - name: See docker compose container running
#        run: docker-compose ps

#      - name: PhpUnit Tests
#        run: |
#          cd www/
#          ls
#          php vendor/bin/phpunit
#        run: |
#          ls
#          docker-compose exec -T app bash
#          vendor/bin/phpunit   