name: CI-laravel

on:
  pull_request:
    branches: 
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Run docker compose
        run: docker-compose up -d

      - name: PhpUnit Tests
        run: |
          docker-compose exec app sh
          vendor/bin/phpunit   